# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # La session démarre uniquement si utilisée
    session:
        enabled: true
        handler_id: null
        storage_factory_id: session.storage.factory.native
        cookie_secure: auto
        cookie_httponly: true
        cookie_samesite: lax

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file