#rate-limiter pour les connexions
framework:
  rate_limiter:
    login:
      policy: 'sliding_window'
      limit: 100
      interval: '1 hour'

    register:
      policy: 'sliding_window'
      limit: 100
      interval: '1 hour'