# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:
    # Stripe
    stripe.secret_key: '%env(STRIPE_SECRET_KEY)%'
    stripe.webhook_secret: '%env(STRIPE_WEBHOOK_SECRET)%'

    # Frontend
    frontend.url: '%env(FRONTEND_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\StripeCheckoutService:
        arguments:
            $stripeSecretKey: '%stripe.secret_key%'
            $frontendUrl: '%frontend.url%'

    App\Controller\Api\StripeWebhookController:
        arguments:
            $stripeWebhookSecret: '%stripe.webhook_secret%'

    App\Controller\Api\CheckoutConfirmController:
        arguments:
            $stripeSecretKey: '%stripe.secret_key%'